version: '3'

services:
  stga:
    build:
      context: ./s3r-stga-ar
      dockerfile: Dockerfile
    image: stga
    ports:
      - "8080:8080"
    networks:
      - s3r-net
    container_name: stga
    labels:
      - traefik.backend=stga
      - traefik.frontend.rule=Host:app.sw-zh-s3r-02.dhlab-basel.ch
      - traefik.docker.network=s3r-net
      - traefik.port=8080

  sipi:
    image: dhlabbasel/sipi:develop
    container_name: sipi
    ports:
      - "1024:1024"
      - "1025:1025"
    volumes:
      - $PWD/config:/sipi/config
      - $PWD/scripts:/sipi/scripts
      - $PWD/images:/sipi/images
      - $PWD/server:/sipi/server
      - $PWD/testDB:/sipi/testDB
      - $PWD/files:/sipi/files
      - $PWD/assets:/sipi/assets
    restart: unless-stopped
    networks:
      - s3r-net
    labels:
      - traefik.backend=sipi
      - traefik.frontend.rule=Host:sipi.sw-zh-s3r-02.dhlab-basel.ch
      - traefik.docker.network=s3r-net

networks:
  s3r-net:
    external:
      name: traefik_proxyNet
      # when running this on your own machine, run 'docker network create --driver bridge traefik_proxyNet'.
      # This creates the external network where the traefik container would reside on the deployment target.
