version: '3'

services:
  stga:
    build:
      context: ./s3r-stga-ar
      dockerfile: Dockerfile
    image: stga
    ports:
      - "8080:8080"
    networks:
      - s3r-net
    container_name: stga

  sipi:
    image: dhlabbasel/sipi:develop
    container_name: sipi
    ports:
      - "1024:1024"
      - "1025:1025"
    volumes:
      - $PWD/Git/S3R/config:/sipi/config
      - $PWD/Git/S3R/scripts:/sipi/scripts
      - $PWD/Git/S3R/images:/sipi/images
      - $PWD/Git/S3R/server:/sipi/server
      - $PWD/Git/S3R/testDB:/sipi/testDB
      - $PWD/Git/S3R/data:/sipi/data
    restart: unless-stopped
    networks:
      - s3r-net

networks:
  s3r-net:
